import { existsSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { generatePrivateKey, privateKeyToAccount } from 'viem/accounts';
import { activeKey, config, warn } from '../config';
import { gasFaucetHelp, gasFaucetLinks, type Faucet } from '../faucets';
import { closeExchanges, getTradingExchange, nativeGasBalance } from '../services/sdk';
import { walletSnapshot, __resetWalletCacheForTests } from '../services/wallet';

/** First-run onboarding for someone running Somnus on their own machine.
 *
 *  The point of the local install is that the operator of the hosted server never
 *  holds anyone's key. This makes that practical: the agent mints itself a fresh
 *  wallet, funds its own trading collateral, and reports what it did — so a new
 *  user goes from `git clone` to a funded testnet account without pasting a
 *  private key anywhere, and without the host taking custody of anything.
 *
 *  There is exactly one thing this cannot do for you, and it is worth being blunt
 *  about rather than discovering at the first failed trade: the SDK's faucet mints
 *  COLLATERAL (tUSDC) only. It has no faucet for the native token that pays gas.
 *  And minting collateral is itself a transaction, so it needs gas first:
 *
 *      new wallet wants tUSDC -> must send a transaction -> transaction needs gas
 *        -> gas is the native token -> a brand-new wallet has none
 *
 *  So the sequence is: create the wallet, have the user drip native gas into it
 *  from Somnia's public faucet (or send some themselves), then the agent funds its
 *  own collateral. One manual step, clearly signposted.                        */

/** Where the generated key is written.
 *
 *  Overridable so this path can be exercised without a test writing a private key
 *  into the real operator's .env — the one file in the repo where a stray write does
 *  lasting damage. Defaults to backend/.env, which is what a local install wants. */
const ENV_PATH =
  process.env.SOMNUS_ENV_PATH || join(dirname(fileURLToPath(import.meta.url)), '..', '..', '.env');

/** Enough native token to be worth attempting anything. One order has cost about
 *  0.004 in practice, so this is a handful of trades — deliberately low, because
 *  the check exists to catch "zero" rather than to demand a big balance. */
const MIN_GAS_TO_PROCEED = 0.01;

/** What to actually TELL somebody to claim, which is not the same number.
 *
 *  `MIN_GAS_TO_PROCEED` is the floor for attempting the collateral mint — it catches
 *  "zero". But the venue reserves a worst-case fee of roughly 0.6 against the balance
 *  before it accepts a trade, so a wallet funded to 0.01 mints collateral and then
 *  cannot trade. Advising the trading number avoids a second trip to the faucet. */
const MIN_GAS_TO_PROCEED_HINT = 0.7;

export interface WalletCreation {
  created: boolean;
  address: string;
  envPath: string;
  note: string;
  /** Where to claim gas, as data — present on testnet only. */
  faucets?: Faucet[];
}

/** Create a wallet and persist it, or report the one already configured.
 *
 *  Never overwrites an existing key. Silently replacing a funded wallet's key would
 *  orphan its balance and its open positions with no way back, so an existing
 *  `TRADE_KEY` always wins and the caller is told the wallet already exists. */
export function createLocalWallet(): WalletCreation {
  const existing = activeKey();
  if (existing) {
    const address = privateKeyToAccount(existing).address;
    return {
      created: false,
      address,
      envPath: ENV_PATH,
      note: 'A wallet is already configured — keeping it. Replacing a key would orphan any balance and open positions it holds.',
    };
  }

  const key = generatePrivateKey();
  const address = privateKeyToAccount(key).address;

  // Written to disk rather than returned to the caller: this runs over MCP, and an
  // MCP tool result is conversation content — it gets stored in history and may be
  // logged. A private key must not travel that channel even once.
  const existingEnv = existsSync(ENV_PATH) ? readFileSync(ENV_PATH, 'utf8') : '';
  const lines = existingEnv.length > 0 && !existingEnv.endsWith('\n') ? `${existingEnv}\n` : existingEnv;
  writeFileSync(
    ENV_PATH,
    `${lines}\n# Generated by somnus_setup — this key never left this machine.\nTRADE_KEY=${key}\nNETWORK=testnet\nDRY_RUN=true\nAGENT_MODE=dry-run\n`,
    'utf8',
  );
  // The process read its config at import time, so the new key is not live until a
  // restart. Say so plainly instead of letting the next tool call fail confusingly.
  //
  // The faucet links go here, on the FIRST-RUN path, because this is the moment a
  // brand-new wallet has nothing: zero gas, zero collateral, and no way to get either
  // without visiting a faucet. Telling somebody at the next failed call is a round trip
  // they did not need.
  const faucets = gasFaucetHelp(address, MIN_GAS_TO_PROCEED_HINT);
  return {
    created: true,
    address,
    envPath: ENV_PATH,
    note:
      `Key written to ${ENV_PATH} and never returned over this channel — an MCP result is ` +
      'conversation content and gets stored. Restart Somnus for the new key to take effect.\n\n' +
      `This wallet is brand new, so it holds nothing at all. Next step is gas.\n\n${faucets ?? ''}`.trimEnd(),
    ...(faucets ? { faucets: gasFaucetLinks()?.faucets } : {}),
  };
}

export interface FundResult {
  address: string;
  gasBefore?: number;
  gasCode?: string;
  collateralBefore?: number;
  collateralAfter?: number;
  collateralCode?: string;
  txHash?: string;
  funded: boolean;
  needsGas: boolean;
  message: string;
  /** Where to claim gas, as data — present only when gas is what is missing. */
  faucets?: Faucet[];
}

/** Mint trading collateral to the configured wallet.
 *
 *  Testnet only, and gated on gas because the mint is itself a transaction. The
 *  faucet is rate-limited per address, so a second call on a funded wallet is
 *  expected to revert — that is reported as a plain outcome, not an error. */
export async function fundCollateral(): Promise<FundResult> {
  if (config.network !== 'testnet') {
    return {
      address: '',
      funded: false,
      needsGas: false,
      message: `The faucet is testnet-only and NETWORK is "${config.network}". Fund this wallet yourself.`,
    };
  }

  __resetWalletCacheForTests();
  const before = await walletSnapshot(true);
  // No key means nothing to fund. This used to cast straight through `as string`
  // and blow up inside viem on `.startsWith` of undefined; say what is wrong instead.
  const key = activeKey();
  if (!key) {
    return {
      address: '',
      funded: false,
      needsGas: false,
      message:
        'No wallet is configured, so there is nothing to fund. Run somnus_setup first to create ' +
        'one (it writes TRADE_KEY to backend/.env and never returns the key over this channel).',
    };
  }
  const address = privateKeyToAccount(key).address;

  const gas = before.native ?? Number(await nativeGasBalance()) / 1e18;
  if (!(gas >= MIN_GAS_TO_PROCEED)) {
    return {
      address,
      gasBefore: gas,
      gasCode: before.nativeCode,
      funded: false,
      needsGas: true,
      message:
        `This wallet holds ${gas.toFixed(6)} ${before.nativeCode ?? 'native token'} and needs gas before it ` +
        'can do anything. The SDK has no faucet for the gas token — only for collateral — and minting ' +
        'collateral is itself a transaction, so this is the one step that cannot be automated for you.' +
        `\n\n${gasFaucetHelp(address, MIN_GAS_TO_PROCEED_HINT, before.nativeCode) ?? ''}` +
        '\n\nThen run somnus_setup again.',
      ...(gasFaucetLinks() ? { faucets: gasFaucetLinks()?.faucets } : {}),
    };
  }

  const exchange = getTradingExchange();
  const tx = (await exchange.trader.faucet()) as { hash?: string; receipt?: { status?: string } };
  if (tx?.receipt?.status === 'reverted') {
    const now = await walletSnapshot(true);
    return {
      address,
      gasBefore: gas,
      gasCode: before.nativeCode,
      collateralBefore: before.collateral,
      collateralAfter: now.collateral,
      collateralCode: now.collateralCode,
      txHash: tx.hash,
      funded: false,
      needsGas: false,
      message:
        'The faucet reverted. It is rate-limited per address, so this is the expected answer for a ' +
        `wallet that has already been funded — current balance ${now.collateral ?? '?'} ${now.collateralCode ?? ''}.`,
    };
  }

  const after = await walletSnapshot(true);
  return {
    address,
    gasBefore: gas,
    gasCode: before.nativeCode,
    collateralBefore: before.collateral,
    collateralAfter: after.collateral,
    collateralCode: after.collateralCode,
    txHash: tx?.hash,
    funded: true,
    needsGas: false,
    message: `Funded. Collateral is now ${after.collateral ?? '?'} ${after.collateralCode ?? ''}. Still in dry-run — nothing can reach the chain until you switch mode to live.`,
  };
}

/** Close SDK sockets opened during setup. The SDK holds the event loop open on a
 *  chain WebSocket, which matters for a stdio server the host may want to exit. */
export async function closeSetupClients(): Promise<void> {
  try {
    await closeExchanges();
  } catch (err) {
    warn('setup: could not close SDK clients:', (err as Error).message);
  }
}
